# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ProyectosVivaldo/p5_avanzado/p5_avanzado.srcs/sources_1/ip/memoria1/memoria1.xci
# IP: The module: 'memoria1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ProyectosVivaldo/p5_avanzado/p5_avanzado.srcs/sources_1/ip/memoria1/memoria1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memoria1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/ProyectosVivaldo/p5_avanzado/p5_avanzado.srcs/sources_1/ip/memoria1/memoria1.xci
# IP: The module: 'memoria1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ProyectosVivaldo/p5_avanzado/p5_avanzado.srcs/sources_1/ip/memoria1/memoria1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memoria1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
