# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ProyectosVivaldo/maquina_tragaperras/maquina_tragaperras.srcs/sources_1/ip/memoria2/memoria2.xci
# IP: The module: 'memoria2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ProyectosVivaldo/maquina_tragaperras/maquina_tragaperras.srcs/sources_1/ip/memoria2/memoria2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memoria2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/ProyectosVivaldo/maquina_tragaperras/maquina_tragaperras.srcs/sources_1/ip/memoria2/memoria2.xci
# IP: The module: 'memoria2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ProyectosVivaldo/maquina_tragaperras/maquina_tragaperras.srcs/sources_1/ip/memoria2/memoria2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memoria2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
