CREATE TABLE t(x) AS
  SELECT 1 UNION ALL 
  SELECT 1 UNION ALL 
  SELECT 1 UNION ALL 
  SELECT 2 UNION ALL 
  SELECT 3 UNION ALL 
  SELECT 3;

CREATE TABLE s(x) AS
  SELECT 1 UNION ALL 
  SELECT 1 UNION ALL 
  SELECT 2 UNION ALL 
  SELECT 4;

